source 'https://rubygems.org'

gem 'rails', '4.1.4'

gem 'mysql2'
gem 'jquery-rails'
gem 'kaminari'
gem 'sorcery'
gem 'actionmailer'
gem 'rails_config'
gem 'carrierwave'
gem 'rmagick', require: 'RMagick'
gem "breadcrumbs_on_rails"
gem "squeel", git: "git://github.com/activerecord-hackery/squeel.git"
gem "redis-rails"
gem "rails-backbone"
gem "ejs"
gem 'activerecord-import'
gem 'mongoid', '4.0.0', github: 'mongoid/mongoid'
gem 'bson_ext'
gem 'tokenizer', git: 'git@lab.clustium.com:kirari/tokenizer.git'
gem 'redis-namespace', '~> 1.3.0'
gem 'resque'
gem 'almicube', github: 'niaeashes/almicube'
gem "default_value_for", "~> 3.0.0"

group :doc do
  gem 'sdoc', require: false
end

group :development, :test do
  gem 'colorize_unpermitted_parameters'
  gem 'quiet_assets'
  gem 'thin'
  gem 'pry'
  gem 'pry-rails'
  gem 'pry-doc'
  gem 'pry-byebug'
  gem 'pry-stack_explorer'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'hirb'
  gem 'hirb-unicode'
  gem 'bullet'
  gem 'rails-erd'
  gem 'spring'
  gem 'shoulda-matchers'
  gem 'simplecov'

  # for test
  gem 'rspec-rails'
  gem 'factory_girl_rails'
  gem 'database_cleaner', github: 'bmabey/database_cleaner'
  gem 'guard-rspec'
  gem 'guard-cucumber'
  gem 'guard-coffeescript'
  gem 'webrat'
  gem 'capybara', git: 'git://github.com/jnicklas/capybara.git'
end

group :production do
  gem 'unicorn'
end

gem 'sass-rails', '~> 4.0.0'
gem 'compass-rails'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'therubyracer', platforms: :ruby
gem 'jbuilder', '~> 1.2'
gem 'bootstrap-sass'
gem 'less-rails'
gem "silverdot"
gem 'gon'
gem 'rabl-rails'
